export const GLOSSES: Record<string, string> = {
  akaṭa: 'not made; not artificial, natural',
  akaṇa: 'without bran; with the bran removed',
  akata: 'not done',
  akāca: 'without impurity, without flaw; pure, clear; smooth',
  akāma: 'without sensual desire',
  akāmā:
    'against one’s will; whether one wishes it or not; without (previous) intention',
  akāla: 'not the right time, not a suitable time (sometimes: nighttime)',
  akāle:
    'not at the right time, at an unsuitable time (sometimes: at night); out of season',
  akula: 'a non-family, a family that is destroyed or disgraced',
  akuha: 'free from deceit; not fraudulent; genuine',
  akūta: 'not deceitful, not false; not wild, not vicious',
  akopa: 'without agitation or anger',
  akhila: 'free from barrenness; free from rigidity or hostility',
  agaru: 'aloe',
  agāra: 'house; a dwelling place',
  agārā: 'house; a dwelling place',
  agiha: 'homeless, without a house',
  aghāvi: 'being in misery; suffering pain',
  aṅgin: 'having limbs or parts; having a body; who has limbs',
  ajaka: 'a young goat',
  ajikā: '(and ajiyā?) a young she-goat',
  ajina: 'hide',
  aṭaṭa:
    'the name of a hell or place in Avīci (where one suffers for an aṭaṭa (high number) of years)',
  aṭani: 'part of a bed or chair (probably the rails forming the frame)',
  aṭalī: 'having several linings (of a certain kind of shoe)',
  aṇīka: 'an army; troops',
  atiga: 'going beyond; escaping from; transgressing',
  atithī: 'a guest; stranger',
  atīta: 'past',
  atīte: 'in the past',
  atīva: 'very much, exceedingly',
  attan: '(adjective) full, complete (or personal)',
  atthaṁ: 'for the sake of; for the purpose of',
  atthin: 'is exists; is found',
  adaka: 'eater',
  addhan: 'time',
  addhāṁ: '(?)',
  adhama: 'low',
  adhika: 'exceeding',
  adhigā: 'attains, finds; understands',
  adhibhū: 'one who overpowers; lord, master; conqueror',
  adhunā: 'now',
  anaṇa: 'free of debt; independent',
  anaya: 'bad course; misfortune, calamity; loss',
  anāgu: 'blameless',
  anādā: 'not taking; not receiving',
  anāsa: 'lack of expectation; lack of desire',
  anīgha: 'free from affliction, from misery; free from trouble',
  anila: 'wind',
  anīka: 'an army; troops',
  anīti: 'freedom from calamity; health, safety',
  anuga: 'going after, following, accompanying (+ genitive)',
  anūna: 'complete',
  aneka: 'many',
  aneja: '(adjective) unmoved, imperturbable; without emotion',
  anoka: '(neuter) homelessness; independence',
  apaca: '“not cooking”, homeless',
  apara: 'another, a further, one more; following, subsequent; later; western',
  apāya: 'hell',
  apāyi: 'going away',
  apekhā: 'regard, attention, longing for (locative)',
  apekhi: 'regardful of; looking for',
  apeta: 'gone away, departed (from); rid of; deprived of',
  apeti: 'goes away; departs',
  apesi: 'a kind of gate or hurdle',
  ababa:
    'the name of a hell, or place in Avīci, where one suffers for an ababa of years',
  abbhuṁ: 'an exclamation of horror or fright or aversion',
  abhito: 'round',
  abhido: 'near, towards',
  abhibhū: 'conqueror',
  amama: 'without possessiveness, without egotism; unselfish',
  amara: 'deathless',
  amuka: 'such and such a person or thing',
  amhan: 'a stone',
  ayati:
    'goes; goes towards; reaches, obtains; reaches (a state); is involved (in)',
  ayasa: 'disgrace',
  araha: 'worthy',
  ariya: '(adjective) belonging to the Ariya people',
  aruka: 'a sore',
  aruṇa: 'dawn',
  alasa: 'idle',
  alāta: 'brand',
  alāpu: '(the fruit of) the bottle-gourd',
  alābu: 'gourd',
  alika: 'lie',
  aviha: '(neuter) the world of the Aviha devas',
  aveti: 'understands; knows',
  avedhi: 'not trembling',
  asati: 'eat',
  asana: 'eating',
  asanī: 'a thunderbolt; a lightning flash',
  asita: 'eat',
  asīti: 'eighty',
  asuka: 'such and such',
  asura: 'one of a class of supernatural beings, opposed to the devas; a titan',
  asman: 'a stone',
  ahaha: 'o',
  ākāra: 'manner',
  ākāsa: 'sky',
  ākhīṇa: 'scattered, unrestrained; rough; impure',
  āgata: '(neuter) arrival; coming',
  āgati: 'arrival, coming; return, rebirth',
  āgama: '(adjective) coming, approaching, next',
  āgāmi: 'approaching; coming, future; returning; being reborn',
  āghāta: 'ill-will, hatred, resentment',
  ācama: 'sipping; rinsing',
  ācaya: 'piling up; collection, accumulation; growth',
  ācāra: 'conduct',
  ājīva: 'subsistence',
  ātapa: 'sunlight; heat of the sun; heat light',
  ātāpi: 'zealous, exerting oneself; zeal; exertion',
  ātuma: 'the self; oneself',
  ātura: 'sick, ill; suffering, afflicted; wretc.hed',
  ādāta: 'one who takes, who receives',
  ādāna: 'taking',
  ādāya: '(the adopting of) a belief, a view',
  ādāsa: 'mirror',
  ādito: 'at first',
  ādiso: 'from the beginning; at first; at the beginning; as a beginning',
  ādeti:
    'takes, accepts, receives; takes up, undertakes; appropriates; seizes, grasps',
  ādeva: 'lamenting; deploring',
  ādhāna:
    'depositing, placing; a container, a receptacle; establishing, kindling (afire)',
  ādhāya:
    'having placed on; having fixed, settled; having established; having accepted, received',
  ādhāra: 'hold',
  ānīta: 'led near; brought; fetc.hed, brought home',
  āneti: 'bring',
  āpagā: 'river',
  āpaṇa: 'market',
  āpadā: 'distress',
  āpadī: 'misfortune; distress; calamity',
  āpātha:
    '‘area over which one moves’, region, sphere, range; field of perception',
  ābādha: 'disease',
  ābhaṭa: 'brought, carried; handed down, transmitted',
  ābhata: 'brought, carried; handed down, transmitted',
  ābhāti: 'shines; irradiates, illumines',
  ābheti: 'shines; irradiates, illumines',
  ābhoga: 'enjoyment, satiety; fullness, completion',
  āmata: 'almost dead, near to death',
  āmisa: 'food',
  āyata: 'long',
  āyati: 'future',
  āyasa: 'made of iron',
  āyāga: 'offering, gift; sacrificial fee; the recipient of an offering',
  āyāti: 'come',
  āyāma: 'length',
  āyāsa: 'trouble',
  āyuda: 'giving life',
  āyuva: 'long lived',
  āyūha: 'thrusting; striving; exertion',
  āyoga: 'binding; a bandage',
  āraka: 'distant, far from',
  ārati: 'abstinence; keeping away from; aversion',
  ārāma: 'park',
  ālaya: 'settling-place, abode; nest, lair; house, hall, shelter; repository',
  ālepa: 'anointing; ointment',
  āloka: 'light',
  ālopa: 'bit',
  āvaṭa: 'cover',
  āvāsa: 'home',
  āvāha: 'bringing home (a bride); marriage (of a son)',
  āvila: 'turbid, not clear; disturbed; polluted',
  āvuṭa: 'covered, encompassed; obstructed; shut, shut off',
  āvuta: 'threaded through; inserted',
  āvudha: 'weapon; weaponry',
  āvuso:
    'respectful term of address, used by and to non-Buddhists, and by bhikkhus (and bhikkhunīs) to lay-followers, and to each other. Not used by or to the Buddha, and later used only by a senior bhikkhu to a junior',
  āveṇi: 'separately, apart; or not united, separate',
  āveni: 'separately, apart; or not united, separate',
  āvelā: 'garland',
  āsada: 'approach; attack, attacking',
  āsana: 'seat',
  āsabha:
    'coming from or produced from a bull; bull-like; belonging to a leader; lordly',
  āsaya: 'haunt',
  āsava: 'spirit',
  āsīna: 'encounters; approaches with (physical or verbal)',
  āhaṭa: 'brought; conveyed; related, cited',
  āhata: 'brought; conveyed; related, cited',
  āhari: 'spoken; declared, related; quoted',
  āhāra: 'food',
  āhāsi: 'spoken; declared, related; quoted',
  āhita: 'fixed, established; kindled, provided with fuel',
  āhuta: 'produced, coming from',
  āhuti: 'offering; sacrifice',
  āhuna: 'offering; honoring',
  itara: 'other',
  itiha: 'thus indeed; so it seems; according to tradition',
  itthaṁ: 'thus',
  idāni: 'now',
  iriṇa: 'desert, inhospitable region; barren or salt soil (also metaphor.',
  iriyā: 'conduct; deportment, life, way of life; movement',
  isikā:
    'the inner part of a reed or stalk (used as an arrow shaft); a stalk of grass',
  isīkā:
    'the inner part of a reed or stalk (used as an arrow shaft); a stalk of grass',
  īdisa: 'of such a kind, such; such and such; like this',
  īsikā:
    'the inner part of a reed or stalk (used as an arrow shaft); a stalk of grass',
  ujuka:
    'straight, direct; straightforward; upright, honest, right; right-minded',
  utunī:
    'menstruating; liable to menstruate; in the (subsequent) fertile period, fertile',
  udaka: 'water',
  udadhi: 'ocean',
  udaya: 'rise',
  udara: 'stomach',
  udāna: '(m. neuter) a joyful or inspired utterance (often in verse)',
  udāhu: 'or',
  udeti: 'rise',
  uddhaṁ: 'high',
  upagā: 'approached; arrived at; (also upāgā)',
  upadhi:
    'worldly possessions or belongings, acquisitions (according to commentaries including the body); attachment to such possessions (forming a basis for rebirth)',
  upamā: 'simile',
  upaya: '(masculine) going near to, involvement',
  upari: 'above',
  upāgā: 'approached; arrived at; (also upāgā)',
  upāya: 'way',
  upeta: '(passive) reached, accepted',
  upeti:
    'approaches, comes or goes to, arrives at, reaches; enters into (a state), undergoes',
  ubbhaṁ: 'upwards; in height; above',
  ubhato: 'in both ways, in both respects; on both sides (of, accusative)',
  ubhaya: 'both',
  uraga: 'creeping animal',
  ulāra: 'lofty, great; excellent, best; noble, illustrious; eminent',
  uḷāra: 'lofty',
  uḷūka: 'an owl',
  usabha: 'leading bull',
  usīra: 'fragrant root of andropogon muricatus',
  usūyā: 'envy',
  usman: 'heat, glow; ardor',
  ūnaka: 'less',
  ūsara: 'saline',
  ūhata: 'soiled (with excrement)',
  ekaka: 'single',
  ekaja: 'born once',
  ekato: 'together',
  ekadā: 'once',
  ekāki: 'alone, solitary',
  ekeka: 'each',
  ekodi: 'woven into one’, integrated, unified; withdrawn, apart',
  etāva: 'so great, of such extent',
  edisa:
    'like this, like so; such a …; of such a kind; such a thing, something like this',
  edhati: 'finds; obtains',
  eragu: 'a kind of grass',
  erita: 'moved, stirred',
  ereti: '(also erayati) makes move, stirs; makes sound; raises one’s voice',
  eḷaka: 'goat',
  eḷakā: 'an ewe; a female goat; a nanny-goat',
  eḷakī: 'an ewe; a female goat; a nanny-goat',
  esati: 'search',
  esana: 'probing',
  esanā: 'probing',
  esanī: 'a probe',
  esikā: 'a post, a pillar (usually placed at the city gate;)',
  okāra: 'degradation, demeaning',
  okāsa: 'room',
  ogaṇa:
    'consisting of a small company; accompanied by a small (or no) company',
  ogata: 'learnt, understood',
  ogadha: 'firm footing in water, firm ground',
  ogāha: 'a bathing place',
  oghana:
    'a pushing downwards, downwards pressure; a thick or dense entanglement',
  ocita: 'collect',
  ojava: 'vigorous, strong; sappy; juicy',
  oñāta: 'despised; underrated',
  oṇata: 'who has bent down, bowed',
  oṇīta:
    '(also onīta) put into water; washed; (according to commentaries) removed; put away',
  otata: 'overspread; covered',
  otāra: 'access',
  odaka: '(neuter) water',
  odana: 'boiled rice',
  odāta: 'white',
  odhiso: 'limitedly',
  odheti:
    'places (in); lays down; applies; directs, especially ~ati sotaṁ, gives ear attentively',
  onata: 'who has bent down, bowed',
  onāha: 'covering; shrouding',
  onīta:
    '(also oṇīta) put into water; washed; (according to commentaries) removed; put away',
  opāta: 'a hole or pit, a trap',
  opiya: 'having thrown or scattered into or onto',
  opeti: 'throws into, heaps up (in)',
  ophuṭa: 'filled, pervaded by; encompassed by; possessed by',
  ophuta: 'filled, pervaded by; encompassed by; possessed by',
  obhāsa: 'light',
  obhoga: 'fold, coil',
  omaka: 'inferior',
  omasa: 'piercing, striking, attacking (verbally)',
  omāti: 'measures up to; is able, is capable (of)',
  omāna: 'contempt; self disgust, self despising',
  orena: 'on this side (of); within, in less than; to this side, over here',
  oraka: 'inferior',
  orato: 'on this side (of), on the nearer side; before',
  orasa: 'legitimate',
  orima: 'nearest, nearer; on this side',
  orodha: 'harem',
  ovaṭa: 'checked; prevented',
  ovadī: 'gave advice; admonished',
  ovāda: 'advice',
  ovuṭa: 'covered; encompassed; checked, obstructed',
  ovuta: 'covered; encompassed; checked, obstructed',
  osaṭa: 'gone down to; having entered',
  osadha: 'medicine',
  osadhī: 'plant',
  osāna: 'end',
  oseti: 'lays down; places, deposits',
  ohaṭa: 'take away, removed',
  ohata: 'take away, removed',
  ohāya: 'leaving behind; abandoning',
  ohāri: 'carrying down; dragging down; carrying off, plundering',
  ohita: 'laid down',
  ohīna: 'left behind',
  'ka ci': 'ka + ci repeated; of whatever kind; of some kind or other',
  kaṁsa: 'plate',
  kakka: 'sediment',
  kaṅka: 'a heron',
  kaṅkhā: 'doubt',
  kaṅkhi: 'desiring, hoping for',
  kaṅgu: 'millet',
  kacci: '“kacci … na …” I hope that… not …; surely … not…',
  kaccha: 'marshy land',
  kacchā:
    'a girdle, belt, especially the girth of an elephant; the end of the lower garment (brought up behind and tucked into the waistband)',
  kacchū: 'the itch, scabies',
  kaññā: 'girl',
  kaṭṭha: 'till',
  kaṇṭha: 'neck',
  kaṇḍa: 'shaft',
  kaṇḍu: 'itching, an itch',
  kaṇṇa: 'ear',
  kaṇha: 'black',
  kataṁ:
    '+ instrumental, done with …; (there is) enough; (there is now) no need of',
  katuṁ: 'doing, acting',
  kattā: 'having done or made',
  kattha: 'where',
  katthi: 'boasting; boastful',
  katvā: 'having done or made',
  kathaṁ:
    '(before vowels sometimes kath’) how? in what way? how is it that …? what … like?; kathaṁ is often followed by one or more particles: katham preceded by yathā, however? in what way',
  kanta: '(past participle adjective) spun',
  kappa: 'a (limited) length of time',
  kamma: 'deed',
  kalya:
    'healthy; in good spirits; sound, fit; ready (for); capable, clever; proper, fitting',
  kalla: 'sound',
  kasmā: 'why?',
  kahaṁ: 'where',
  kāmaṁ: 'surely',
  kicca: 'work',
  kiccha: 'difficult',
  kicchā: 'with difficulty; with great trouble',
  kiṭṭha: 'growing corn',
  kiṇṇa: 'yeast',
  kiṇha: 'black, dark; wicked',
  kitti: 'renown',
  kinti: 'whether',
  kissa: 'why?',
  kīvat: 'how great? how many? of what qualities?',
  kīvaṁ:
    'how much? to what extent? how …? how …! (kiva can be interpreted as an adverb modifying an adjective or adverb, or as forming a compound with an adjective or adverb)',
  kukku: 'cubit',
  kucchi: 'belly',
  kuṭṭa: '(another way of writing kuḍḍa) a wall',
  kuṭṭha: 'a kind of leprosy; a sore',
  kuṭṭhi: '(one) suffering from a skin disease; leprosy',
  kuḍḍa: 'wall',
  kuṇḍa: 'bran',
  kutta: 'coquetry',
  kuddha: 'angry',
  kuppa: '(neuter) disturbance',
  kumbha: 'pot',
  kumbhi: 'a pot; a cooking vessel',
  kumbhī: 'a pot; a cooking vessel',
  kumma: 'tortoise',
  kulla: 'raft',
  kuvaṁ: 'where?',
  kuhiṁ: 'where',
  kesin: 'having fine or long hair',
  'ko ca':
    'in the same construction, with two nouns, ko is taken as from ka and made to agree with its noun',
  'ko ci': 'somewhere; anywhere; in some place',
  koccha: 'brush',
  koñca: 'a trumpeting noise',
  koṭṭha: 'the stomach; the abdomen',
  koṭṭhu: 'a jackal',
  kotthu: 'a jackal',
  kriyā: 'morally significant activity which produces effects',
  klesa:
    'affliction; distress; especially that which afflicts, that which stains; an affliction, a defilement; a defiling passion, especially sexual desire, lust',
  kvaci: 'anywhere; in anything; somewhere, in some places; sometimes',
  khagga: 'sword',
  khajja: '(adjective) to be eaten; (neuter) solid hard food; a cake; pastry',
  khañja: 'lame',
  khaṇḍa: 'bit',
  khatta: '(masculine) a digger; one who digs',
  khanta: 'pardon',
  khanti: 'patience',
  khantī: 'patience; forbearance; endurance',
  khandha: 'bulk',
  khambha: 'a prop, a support',
  khiḍḍā: 'play',
  khitta: 'throw',
  khippa: '(adjective) quick; swift',
  khīṇaṁ: 'hurtfully, roughly',
  khujja: 'humpbacked',
  khudda: '(neuter (& adjective?)) honey',
  khetta: 'field',
  khemin: 'safe, secure; enjoying peace and security',
  gaccha: 'plant',
  gaṇṭhi: 'knot',
  gaṇḍa: 'boil',
  gatta: 'body',
  gantha: 'composition',
  gandha: 'odour',
  gabbha: 'chamber',
  gamma: 'vulgar',
  gāḷha: 'tight',
  gijjha: 'vulture',
  giddha: 'greedy',
  gimha: 'the heat of summer',
  gutta: 'guarded; protected; watchful; protector; defender; preserver',
  gutti: 'guard',
  gundā: 'the rush nut, cyperus rotundus',
  gumba: 'bush',
  guyha:
    'what is to be covered or concealed; the parts of the body which to be covered, especially the private parts; what is to be kept secret, secret; private; a secret',
  geyya: 'the name of one of the nine categories (aṅgas) of the scriptures',
  goṭṭha: 'a cow pen; a cattle-fold',
  gotta: 'clan',
  goppha: 'the ankle',
  ghamma: 'heat',
  cakka: 'wheel',
  cakkhu: 'eye',
  catta: 'given up',
  caṇḍa: 'fierce',
  canda: 'moon',
  candī: 'belonging to the moon (?)',
  camma: 'hide',
  ciṇṇa:
    '(neuter) practicing observance; conduct; habitual conduct or practice',
  citta: 'mind',
  cintā: 'thought',
  ciraṁ: 'long',
  cuṇṇa: 'powder',
  culla: 'a fireplace; a hearth',
  chakka: 'a set of six; a section of sets of six',
  chaṭṭha: 'sixth',
  chatta: 'umbrella',
  channa: 'cover',
  chamāṁ: 'on the ground; to the ground',
  chidda: 'hole',
  chinna: 'cut',
  chuddha: 'thrown away, rejected, abandoned',
  chejja:
    '(neuter) fit to cut off; liable to break; (neuter) cutting; cutting off; cutting off one’s limbs; cutting off from the saṅgha',
  chejjā: 'cutting off; cutting',
  cheppā: 'the tail',
  jaṅghā: 'calf',
  jaṇṇu: 'knee',
  jantu: 'being',
  jambu: '(feminine) the rose apple tree',
  jamma: 'contemptible, low; of low birth; a contemptible person, a wretc.h',
  jalla: 'dirt; scum; dirt from sweat',
  jānaṁ: 'knowingly; with knowledge',
  jiṇṇa: 'old',
  jitvā: 'having conquered; having subdued',
  jimha:
    'oblique; slanting; not straight, not on the right line; dishonest, false; (what is not straight(?))',
  jivhā: 'tongue',
  juṇhā: 'moonlight; a moonlit night',
  jeṭṭha: 'elder',
  jetvā: 'having conquered; having subdued',
  jeyya: 'should be conquered',
  jhatta: 'consumed, dried up; weakened',
  jhatvā: '(absolutive) having burnt',
  ñatta:
    'skill or accomplishment; a public reputation (for skill or intellectual accomplishment)',
  ñatti: 'proposal, motion (for an official act of the saṅgha)',
  ñeyya: 'to be known; knowable; being an object of knowledge',
  ḍaṁsa: 'a gadfly; a stinging insect',
  ḍaṭṭha: 'bitten',
  taggha:
    'indeed; certainly; ~ especially confirming a previous statement or question',
  taccha: 'real',
  tajja:
    'coming from or belonging to or relating to him/her/that; of the same kind; appropriate to that',
  taṇhā: 'craving',
  tatta: 'heated; hot; made red hot; molten',
  tattha: 'there',
  tatra: 'there',
  'ta(d)': 'as adjective: that',
  tadaṁ: 'that',
  tanta: 'thread',
  tanti: 'a tendon; a string',
  tandi: 'lassitude; laziness; sloth',
  tandī: 'sloth',
  tasmā: 'therefore',
  tahaṁ: 'there',
  tahiṁ: 'there',
  tiṁsa: 'thirty',
  tikkha: 'sharp',
  tiṇṇa: 'cross',
  tiṇha: 'sharp',
  titta: 'bitter',
  titti: 'satisfaction',
  tittha: '(metaphor.) a ford, a way across; a dogma; a sect',
  tippa: 'sharp',
  tibba: 'sharp',
  tuccha: 'empty',
  tuṭṭha: 'pleased, content, satisfied',
  tuṭṭhi: 'joy',
  tuṇḍa: 'snout',
  tuṇhī:
    'silently; (without verb) (there is) silence; especially tuṇhī bhavati, is silent',
  tutta: 'a pike or goad for guiding elephants',
  tunna: 'prick',
  tumba: 'a kind of water vessel',
  tulya: 'equal',
  thañña: 'mother’s milk',
  thaddha: 'hard',
  thamba: 'a tuft or clump of grass',
  thambha: 'pillar',
  thulla: 'fat',
  theyya: 'theft',
  dakkha: 'clever',
  daṭṭha: 'bitten',
  daḍḍha: 'burn',
  daṇḍa: 'stem',
  datta: 'mad; foolish; wild; arrogant',
  datti: 'a gift (of food); (according to commentaries) a small bowl)',
  daddu: 'a kind of cutaneous eruption; a skin disease',
  danta: 'tame',
  dandha: 'slow',
  dabba: 'substance',
  dabbī: 'a ladle; a spoon',
  dabbha: 'kusa grass',
  daḷha: 'firm',
  diṭṭha: 'seen',
  diṭṭhā: 'thank heavens! what luck!',
  diṭṭhi: 'dogma',
  ditta: 'blaze',
  diddha: 'smeared; poisoned',
  dinna: 'given',
  dibba: 'divine',
  dīghaṁ: 'long',
  dukkha: 'suffering',
  dugga: 'fort',
  duṭṭha: 'corrupt',
  dubbha: 'injuring, hurting, deceiving',
  dussa: 'cloth',
  dūraṁ: 'a long way; far',
  deyya: 'to be given; there must be giving; a gift',
  dessa: 'to be hated; hateful',
  dvaya: '(neuter) a pair, two things',
  dvāra: 'door',
  dvika: 'a dyad; pair; couple',
  dvija: 'one (who) is born or produced twice; ~ especially a bird',
  dvidhā: 'in two ways',
  dvīha: 'two days',
  dhaṅka: 'a crow',
  dhañña: 'corn',
  dhanta: 'blow',
  dhamma: 'doctrine',
  dhammī: 'connected with dhamma',
  dhutta: 'a gambler; a bad character; a cheat, a scoundrel, a rake',
  dhuttī:
    'a deceitful or wanton woman; (adjective) cheating; dissolute; immoral',
  nakka: 'a crocodile',
  nagga: 'naked',
  nacca: 'play',
  naṭṭha: 'perish',
  natthi: 'it is not; there is not',
  natthu: 'into the nose',
  naddhi: 'thong',
  nandi: 'pleasure',
  nicca: 'constant',
  niṭṭhā: 'death',
  niddā: 'sleep',
  nindā: 'blame, criticism; fault-finding',
  ninna: 'low',
  nunna: 'impelled; driven away, dispelled, removed',
  nekkha: 'made of gold; gold; a coin or ornament made of gold',
  netta: 'eye',
  paṁsu: 'soil',
  pakka: 'ripe',
  pakkha: 'side',
  pakkhī: 'bird',
  paṅka: 'mire',
  paṅgu: 'lame; a cripple',
  pacci: 'was cooked; suffered',
  pacchā: 'afterwards',
  pacchi: 'a hand-basket',
  pajja: 'verse',
  pañca: 'five',
  pañña: 'wise; endowed with knowledge. (in compounds)',
  paññā: 'wisdom',
  pañha: 'question',
  paṭṭa: 'plate',
  paṇḍu: 'pale-yellow; yellowish',
  paṇṇa: 'leaf',
  paṇya: 'a trader',
  paṇhi: 'heel',
  patta: 'reach',
  patti: 'infantry',
  pattha: 'a measure of grain or liquid, four of which make a seer. See pasata',
  patvā: 'having reached; attained or obtained',
  padma: 'a lotus; name of purgatory and that        of an enormous number',
  panta: 'distant; remote; secluded; solitary',
  panti: 'row',
  pantha: 'path',
  panna: 'fallen; gone down',
  pabba: 'joint',
  pamha: 'the eye-lash',
  paraṁ: 'after',
  passa: 'side',
  passi: 'saw; found; understood',
  pātuṁ: 'to drink',
  pāraṁ: 'beyond',
  piṁsi: 'ground; crushed',
  piccha: ' tail-feather;',
  piñja: 'feather',
  piṭṭha: 'surface',
  piṭṭhi: 'the back; upper side; top',
  piṇḍa: 'lump',
  piṇḍī: 'a cluster; bunch',
  pitar: 'father',
  pitta: 'bile',
  puṅkha: 'Err:509',
  puccha: 'tail',
  pucchā: 'question',
  pucchi: 'asked; questioned',
  pujja: 'honourable',
  puñchi: 'wiped off; cleaned',
  puñja: 'heap',
  puñña: 'merit',
  puṭṭha: 'nourish',
  puṇṇa: 'full',
  putta: 'son',
  puppha: 'flower',
  pupphi: 'flowered; was blown',
  pubba: 'pus',
  pubbā: 'the east',
  pubbe: 'formerly; in the past',
  pekkhi: 'saw; looked at',
  pecca: 'after death',
  peyya: 'drinkable',
  pessa: 'messenger',
  poṅkha: 'Err:509',
  plava: 'floating; a raft',
  plavi: 'floated; moved quickly; swam',
  phaggu: 'period of fasting',
  phandi: 'trembled; throbbed; stirred',
  phassa: 'touch',
  phuṭṭha: 'touch',
  phulla: 'fully opened or expanded; full of blossoms',
  phussa: 'January',
  pheggu: 'wood surrounding the pith of a tree; a worthless thing',
  baddha: 'bound',
  bandha: 'bound; fetter; attachment; imprisonment',
  bandhi: 'combined; united',
  bandhu: 'kinsman',
  babbu: 'cat',
  bālya: 'childhood',
  bāḷha: 'strong; much; excessive',
  bindu: 'drop',
  bimba: 'disk',
  bimbā: "name of the Prince Siddhartha's wife",
  bimbī: 'the creeper brayonia grandis, which produces red oval fruits',
  billa: 'marmelo',
  bujjhi: 'knew; understood; perceived',
  buḍḍha: 'aged; old',
  buddha: 'one who has attained enlightenment; the Enlightened One',
  buddhi: 'wisdom',
  bondi: 'the body',
  byāma: 'a fathom',
  byūha: 'array',
  brūti: 'say',
  bhakkha: 'prey',
  bhakkhi: 'ate; fed upon',
  bhagga: 'broken',
  bhaṅga: 'dissolution',
  bhacca: 'servant',
  bhajji: 'roasted; toasted',
  bhañji: 'broke; destroyed',
  bhaṭṭha: 'roasted; fallen down; dropped',
  bhaṇḍa: 'article',
  bhaṇḍi: 'quarreled',
  bhaṇḍu: 'a person who is shaven',
  bhatta: 'boiled rice',
  bhatti: 'devotion',
  bhadda: 'august; auspicious; lucky; good',
  bhaddā: 'a well-behaved woman',
  bhadra: 'august; auspicious; lucky; good',
  bhanta: 'swaying; swerving; revolved; whirled about; roamed',
  bhante: 'Reverend Sir; O lord',
  bhabba: 'able',
  bhastā: 'bellows',
  bhasma: 'ash',
  bhassa: 'useless talk',
  bhassi: 'fell down; dropped',
  bhāgya: 'luck',
  bhātar: 'a brother',
  bhikkhā: 'alms',
  bhikkhi: 'begged alms; asked for',
  bhikkhu: 'a Buddhist monk',
  bhiṅka: 'a young elephant',
  bhijji: 'broke; destroyed',
  bhitti: 'wall',
  bhindi: 'broke; split; severed',
  bhinna: 'broken',
  bhiyyo: 'exceedingly; more; in a higher degree; repeatedly',
  bhuñji: 'ate; enjoyed',
  bhutta: 'eat',
  bhutvā: 'having eaten; having enjoyed',
  bhumma: 'terrestrial',
  bhusaṁ: 'frequently',
  bhussi: 'barked',
  bhūtvā: 'having existed',
  bhejja: 'brittle; breakable. (neuter), breaking or cutting off',
  bheṇḍu: 'a ball for playing; a ball-shaped top or cupola',
  bhogga: 'bent',
  bhojja: 'edible',
  maṁsa: 'flesh',
  makkha: 'depreciation of another’s worth',
  makkhī: 'one who depreciates another’s worth',
  magga: 'road',
  maggi: 'sought; tracked; traced out',
  maṅku: 'confused; downcast; in low spirits',
  macca: 'man',
  maccu: 'death',
  maccha: 'fish',
  macchī: 'a she-fish',
  majja: 'intoxicant',
  majji: 'intoxicated; polished; wiped; cleaned',
  majjha: 'waist',
  mañca: 'a bed',
  mañju: 'charming; lovely',
  maññi: 'imagined; deemed',
  maññe: 'methinks',
  maṭṭa: 'smooth',
  maṭṭha: 'smooth',
  maṇḍa: 'the best part (of milk, etc.). (adjective), very clear',
  matta:
    'was intoxicated; full of joy; proud of; conceited; polished. (- ka), (in compounds) of the size of; as much as',
  mattā: 'quantity',
  matthu: 'the water separated from the curd',
  maddi: 'crushed; trampled on; subjugated',
  manaṁ: 'well-nigh',
  manta: 'charm',
  mantī: 'a counselor; a minister',
  mantha: 'churning stick',
  manda: 'slow',
  mamma: 'a vital spot of the body; a nerve center',
  mayaṁ: 'we',
  malla: 'a wrestler; a man of the Malla clan',
  massu: 'beard',
  mātar: 'mother',
  mālya: 'a garland',
  micchā: 'wrongly',
  miñja: 'kernel',
  miñjā: 'kernel',
  mitta: 'friend',
  middha: 'torpor',
  middhī: 'drowsy',
  missa: 'mixed; combined',
  mīḷha: 'excrement',
  mukhya: 'chief',
  mugga: 'green peas',
  mucci: 'became free',
  mucchā: 'fainting',
  mucchi: 'became unconscious or infatuated; fainted',
  muñci: 'released; loosened; delivered; sent off; emitted; gave up',
  muñja: 'a kind of grass used in making slippers, etc.',
  muṭṭha: 'forgotten; passed into oblivion',
  muṭṭhi: 'fist',
  muṇḍa: 'shaven; void of vegetation; bare',
  mutta: 'urine',
  muttā: 'pearl',
  mutti: 'release',
  muddā: 'seal',
  muddha: 'foolish; bewildered',
  muddhā: 'summit',
  muyhi: 'forgot; became dull; infatuated',
  mussi: 'forgot; passed into oblivion',
  muhuṁ: 'very quickly',
  mūlya: 'payment; wages',
  mūḷha: 'gone astray; forgotten; confused; erring; foolish',
  mejjha: 'pure',
  meṇḍa: 'ram',
  mettā: 'amity',
  metti: 'amity',
  mokkha: 'release',
  yakkha: 'demon',
  yakkhī: 'a demoness',
  yagghe: 'hortative particle used in addressing a superior person',
  yañña: 'sacrifice',
  yaṭṭhi: 'staff',
  yattha: 'wherever',
  yatra: 'where',
  yanta: 'machine',
  yahaṁ: 'where; wherever',
  yahiṁ: 'where',
  yātrā: 'travel; voyage; support of life',
  yātvā: 'having gone; having proceeded',
  yiṭṭha: 'sacrifice',
  yujjhi: 'fought; made war',
  yuñji: 'joined with; engaged in; endeavored',
  yutta: 'yoked; harnessed; connected with; given to; engaged in; proper',
  yutti: 'justice',
  yuddha: 'fight',
  yogga: 'suitable',
  yotta: 'a string; a twine',
  raṁsi: 'light',
  rakkhā: 'protection; safety; shelter',
  rakkhi: 'protected; guarded; observed; preserved',
  raṅga: 'dye',
  racchā: 'street',
  rajja: 'kingdom',
  rajji: 'found pleasure in',
  rajju: 'rope',
  rañji: 'found delight in',
  raṭṭha: 'country',
  ratta: 'colour',
  ratti: 'night',
  randha: 'an opening; cleft; a weak spot; fault',
  rambhā: 'plantain',
  ramma: 'charming',
  rasmi: 'a cord; a rein; ray of light',
  rassa: 'short',
  riñci: 'neglected; abandoned; emptied',
  ritta: 'devoid',
  rukkha: 'tree',
  rucci: 'found delight in; liked',
  rujjhi: 'was obstructed or prevented',
  ruṭṭha: 'enrage',
  ruṇṇa: 'crying; weeping; lamentation',
  ruddha: 'besiege',
  rundhi: 'prevented; obstructed; besieged; imprisoned',
  ruppi: 'was vexed or changed',
  rūḷha: 'grew; ascended; healed (a wound)',
  lakkha: 'target',
  lakkhī: 'luck',
  lagga: 'attach',
  laggi: 'stuck; attached; adhered to; hung from',
  laṅgī: 'a bolt; a bar',
  laṅghi: 'jumped over; hopped',
  laṅghī: 'a jumper; a threshold',
  lajjā: 'shame',
  lajji: 'was ashamed or abashed',
  lajjī: 'feeling shame; modest; conscientious',
  lañca: 'bribe',
  lañcha: 'a mark; an imprint',
  lañchi: 'marked; stamped; sealed',
  laṭṭhi: 'a staff; a young tree',
  laṇḍa: 'dung of animals',
  laddha: 'obtain',
  laddhā: 'having got, received, or attained',
  laddhi: 'a view of theory',
  labbhā: 'possible; allowable; may be obtained',
  lamba: 'hanging from; pendulous',
  lambi: 'hung down; suspended',
  lahuṁ: 'quickly',
  likkhā: 'an egg of a louse; a measure named after it',
  liṅga: 'feature',
  litta: 'smeared; stained; anointed',
  limpi: 'smeared; stained; anointed',
  lugga: 'broken up; felt apart',
  lujji: 'broke up; felt apart',
  luñci: 'pulled out; uprooted',
  lutta: 'elide',
  ludda: 'fierce; cruel. (masculine), huntsman',
  luddha: 'greedy',
  lubbhi: 'was greedy; coveted',
  lumpi: 'plundered; ate',
  leḍḍu: 'clod',
  leyya: 'fit to be licked or sipped. (neuter), mucilaginous food',
  vaṁsa: 'race',
  vakka: 'kidney',
  vagga: 'group',
  vaggu: 'lovely; pleasant',
  vaṅka: 'crooked',
  vaṅga: 'the country of Bengal',
  vacca: 'excrement',
  vaccha: 'calf',
  vajja: 'fault',
  vajjā: 'he would say',
  vajjī: 'a man of the Vajji clan',
  vajjha: 'fit to be killed or punished',
  vañjha: 'barren',
  vañjhā: 'barren woman',
  vaṭṭa:
    'circular; round. (neuter), a circle; the cycle of rebirth; an expenditure or provision for alms',
  vaṭṭi: 'roll',
  vaṭṭha: 'wet with rain',
  vaḍḍha: 'augmenting; increasing',
  vaḍḍhi: 'growth',
  vaṇṭa: 'stalk',
  vaṇṇa: 'colour',
  vaṇṇī: '(in compounds) having the appearance of',
  vaṇṇu: 'sand',
  vatta: 'service',
  vatti: 'existed; happened; took place; went on',
  vattī: '(in compounds) one who keeps up, practices, or causes to go on',
  vattha: 'cloth',
  vatthi: 'bladder',
  vatthu: 'site',
  vatvā: 'having told or said',
  vaddha: 'old; venerable',
  vanta: 'vomited; renounced',
  vandi: 'saluted; paid homage; honored; adored',
  vappa: 'sowing; name of a month, October-November',
  vambhī: 'one who treats with contempt',
  vamma: 'armour',
  vammī: 'wearing armour',
  vayha: 'litter',
  varaṁ: 'better',
  valli: 'creeper',
  vassa: 'year',
  vassi: 'rained; uttered a cry (by some animal)',
  vākya: 'sentence',
  vijjā: 'knowledge',
  vijju: 'lightning',
  vijjhi: 'shot',
  viññū: 'wise',
  vitta: 'wealth',
  vitti: 'joy; happiness',
  vittha: 'a bowl for drinking spirits',
  viddha: 'pierced; shot; struck',
  vindi: 'enjoyed; underwent; knew; gained',
  vippa: 'a brahman',
  visuṁ: 'separately',
  vuṭṭha: 'rain',
  vuṭṭhi: 'rain',
  vuḍḍha: 'old; venerable',
  vuḍḍhi: 'increase; growth; prosperity',
  vutta: 'sown; shaven',
  vutti: 'conduct; habit; practice; usage; livelihood',
  vuttī: 'having the habit or practice of',
  vuttha: 'live',
  vuddha: 'old; venerable',
  vuddhi: 'increase',
  vuyhi: 'floated',
  vūḷha: 'float',
  vejja: 'physician',
  vetta: 'cane',
  vesma: 'a dwelling place',
  vessa: 'a member of the third social grade',
  vyathi: 'oppressed; subdued',
  vyayo: 'age; loss; decay; expenditure. (see vaya)',
  vyādha: 'huntsman',
  vyādhi: 'sickness',
  vyāma: 'fathom',
  vyūha: 'array',
  saūmi: 'with waves; turbulent',
  sakiṁ: 'once',
  sakka: 'the king of devas',
  sakkā: 'it is possible',
  sakkhi: 'face to face',
  sakkhī: 'witness',
  sakya: 'belonging to the Sākya race',
  sakhya: 'friendship',
  sagga: 'heaven',
  saṅki: 'doubted; hesitated',
  saṅkī: 'doubtful',
  saṅku: 'stake',
  saṅkha: 'conch',
  saṅkhā: 'enumeration; calculation; a number; definition',
  saṅga: 'attachment',
  saṅgha: 'multitude',
  saṅghī: 'having a crowd of followers',
  sacca: 'truth',
  sajji: 'clung to',
  sajju: 'instantly',
  sajjhu: 'silver',
  sañjhā: 'evening',
  saññā: 'sense',
  saññī: 'conscious; having perception; being aware',
  saṭṭha: 'clung to',
  saṭṭhi: 'sixty',
  saṇḍa: 'a grove; cluster; multitude',
  saṇha: 'smooth',
  satta: 'seven',
  satti: 'power',
  sattu: 'enemy',
  sattha: 'science',
  satthi: 'thigh',
  satthu: 'master',
  sadda: 'sound',
  saddha: 'devoted',
  saddhā: 'faith',
  santi: 'peace',
  sanda: 'dense',
  sandi: 'flowed',
  sandhi: 'joint',
  sappa: 'a snake',
  sappi: 'ghee',
  sabba: 'all',
  sabbhi:
    'the virtuous. ((= Sk. sadbhih, with wise, But in Pāli it is sometimes used as an) adj.)',
  samaṁ: 'evenly',
  sampha: 'frivolity; useless talk',
  samma: 'my dear. (a term of familiar address; seen only in vocative)',
  sammā: 'properly',
  sayaṁ: 'oneself',
  sayha: 'bearable',
  salla: 'dart',
  sassa: 'corn',
  sassu: 'mother-in-law',
  sāttha:
    'having a purpose; useful; having a meaning; significant; with its meaning or purpose',
  sāmaṁ: 'oneself',
  sikkā: 'pingo-basket',
  sikkhā: 'discipline',
  sikkhi: 'learnt; trained oneself; practiced',
  siggu: 'horse radish',
  siṅga: 'horn',
  siṅgī: 'possessing horns. (feminine), gold',
  siṅghi: 'sniffed; smelled',
  sijjhi: 'happened; succeeded; availed',
  siñci: 'poured; sprinkled',
  sitta: 'sprinkle',
  sittha: 'wax',
  siddha: 'happen',
  siddhi: 'accomplishment; success',
  sindī: 'the date palm',
  sindhu: 'ocean',
  sippa: 'art',
  sippī: 'artist',
  sibbi: 'stitched; sewed',
  sissa: 'pupil',
  sīghaṁ: 'quickly',
  sukka: 'white',
  sukkha: 'dry',
  sukkhi: 'dried up',
  sukhaṁ: 'easily; comfortably',
  suṅka: 'toll',
  sujjhi: 'became clean or pure',
  suñña: 'empty',
  suṭṭhu: 'well',
  suṇhā: 'a daughter-in-law',
  sutta: 'asleep',
  sutti: 'a pearl oyster',
  sutvā: 'having heard',
  sudaṁ: 'pleonastic particle',
  sudda:
    'a person of the Sūdra caste. (adjective), clean; pure; unmixed; simple',
  suddha: 'clean',
  suddhi: 'purity',
  suppa: 'winnowing basket',
  sussi: 'withered',
  sekkha: 'learner',
  seṭṭha: 'foremost; excellent',
  seṭṭhi: 'a millionaire',
  seṭṭhī: 'a millionaire',
  settha: 'I slept',
  senta: 'sleeping',
  semha: 'phlegm',
  seyya: 'better; excellent',
  seyyā: 'bed',
  seyyo: 'better',
  sokhya: 'health; happiness',
  soṇḍa: 'addicted to',
  soṇḍā: 'an elephant’s trunk; a woman addicted to drink, etc.',
  soṇḍī: 'a natural tank in a rock',
  soṇṇa: 'gold',
  sotar: 'hearer',
  sotuṁ: 'to hear',
  sotthi: 'well-being; safety; blessing',
  soppa: 'sleep',
  sobbha: 'pool',
  somma: 'gentle',
  sneha: 'love',
  haṁsa: 'swan',
  haṁsi: 'bristled',
  haṁsī: 'a swan',
  haññi: 'was killed',
  haṭṭha: 'was joyful; was happy; bristling',
  hattha: 'hand',
  hatthi: 'the shortened form of hatthī (= an elephant)',
  hatthī: 'elephant',
  hanti: 'kills; strikes; injures',
  handa: 'well then',
  hambho: 'a particle used in addressing equals',
  halaṁ: 'enough; why should',
  havya: 'oblation',
  hassa: 'laughter; joke; jest',
  hātuṁ: 'to remove; to give up',
  hiṁsā: 'hurt',
  hiṁsi: 'hurt; injured; teased',
  hikkā: 'hiccup',
  hiṅgu: 'asafoetida',
  hiyyo: 'yesterday',
  hutta: 'sacrifice',
  hutvā: 'having been',
  huraṁ: 'in the other world; in another existence',
  heṭṭhā: 'below',
  hotuṁ: 'to exist',
  honta: 'existing',
  agati: 'prejudice',
  agalu: 'aloe',
  agādha: 'deep',
  aṭavi: 'forest',
  atithi: 'guest',
  adhipa: 'lord',
  adhīna: 'belonging to',
  anala: 'fire',
  anātha: 'helpless',
  anuja: 'brother',
  anujā: 'sister',
  apada: 'footless',
  apāṇa: 'breathing out',
  aphala: 'fruitless',
  abalā: 'woman',
  abhaya: 'safe',
  abhayā: 'yellow myrobalan',
  abhāva: 'disappearance',
  abhīta: 'fearless',
  abhūta: 'falsehood',
  amata: 'ambrosia',
  amarā: 'eel',
  amita: 'boundless',
  amoha: 'wisdom',
  ayana: 'path',
  arisa: 'piles',
  arūpa: 'formless',
  alābha: 'loss',
  avadhi: 'boundary',
  avani: 'earth',
  avelā: 'improper time',
  asaṭha: 'honest',
  asani: 'thunderbolt',
  asesa: 'entire',
  ahosi: 'was',
  ākara: 'mine',
  ākula: 'entangled',
  āgāmī: 'coming',
  ātāpī: 'ardent',
  ādāti: 'take',
  ādima: 'first',
  ānana: 'face',
  āpāna: 'drinking hall',
  āmoda: 'pleasure',
  ālāpa: 'talk',
  āvaha: 'conducive',
  āvāṭa: 'pit',
  āvāpa: 'furnace',
  āsati: 'sit',
  īsaka: 'few',
  īhati: 'strive',
  udita: 'rise',
  ekadhā: 'in one way',
  ekākī: 'lonely',
  ekūna: 'minus one',
  olīna: 'sluggish',
  kacchu: 'itch',
  kanda: 'tuber',
  kabba: 'poem',
  kambu: 'conch',
  kiñci: 'something',
  kuñja: 'glen',
  kuṭṭhī: 'leper',
  kuttha: 'where',
  kutra: 'where',
  gaṅgā: 'river',
  giddhi: 'greed',
  gūḷha: 'secret',
  ghaṇṭā: 'bell',
  ciñcā: 'tamarind',
  jattu: 'shoulder',
  tantu: 'cord',
  tamba: 'copper',
  tinta: 'wet',
  tuṅga: 'prominent',
  tumbī: 'gourd',
  tuvaṁ: 'thou',
  dappa: 'arrogance',
  ditti: 'light',
  duṭṭhu: 'badly',
  duddha: 'milk',
  naṭṭa: 'dance',
  nikkha: 'gold coin',
  niḍḍa: 'nest',
  nyāsa: 'mortgage',
  param: 'the supreme' ,
  sarve: 'all' ,
  karma: 'reward-seeking actions' ,
  tasya: 'his' ,
  yasya: 'whose' ,
  āsīta: 'seated' ,
  namaḥ: 'hail' ,
  kartā: 'the doer' ,
  gurūn: 'teacher' ,
  tatam: 'father' ,

}
